# Generated by Django 2.1.2 on 2018-10-23 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text='Titolo', max_length=200)),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today, editable=False)),
                ('categoria', models.CharField(choices=[('CINEMA', 'Cinema'), ('SCIENZA', 'Scienza'), ('SPORT', 'Sport'), ('CUCINA', 'Cucina'), ('POLITICA', 'Politica'), ('VIAGGI', 'Viaggi')], help_text='Categoria', max_length=8)),
                ('citazioni', models.ManyToManyField(blank=True, to='articolo.Articolo')),
                ('id_autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autore.Autore')),
            ],
            options={
                'get_latest_by': '-data',
            },
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today, editable=False)),
                ('commentatore', models.CharField(help_text='Nick name', max_length=15)),
                ('id_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articolo.Articolo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commento',
            unique_together={('id_articolo', 'id')},
        ),
    ]
