# Generated by Django 2.1.2 on 2018-10-20 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autore', '0002_autore_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('id_autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autore.Autore')),
            ],
            options={
                'get_latest_by': '-data',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articolo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='articolo.Articolo')),
                ('id_articolo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='è_citato', to='articolo.Articolo')),
            ],
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('commentatore', models.CharField(max_length=15)),
                ('id_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articolo.Articolo')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commento',
            unique_together={('id_articolo', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('id_articolo1', 'id_articolo2')},
        ),
    ]
