# Generated by Django 2.1.2 on 2018-10-27 08:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text='Titolo', max_length=200)),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today, editable=False)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), help_text='Puoi inserire max 10 parole chiave per il tuo articolo', max_length=10, size=None)),
                ('categoria', models.CharField(choices=[('CINEMA', 'Cinema'), ('SCIENZA', 'Scienza'), ('SPORT', 'Sport'), ('CUCINA', 'Cucina'), ('POLITICA', 'Politica'), ('VIAGGI', 'Viaggi')], help_text='Categoria', max_length=8)),
                ('citazioni', models.ManyToManyField(blank=True, to='articolo.Articolo')),
            ],
            options={
                'get_latest_by': '-data',
            },
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateField(default=datetime.date.today, editable=False)),
                ('commentatore', models.CharField(help_text='Nick name', max_length=15)),
                ('id_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articolo.Articolo')),
            ],
            options={
                'verbose_name_plural': 'Commenti',
            },
        ),
    ]
