# Generated by Django 2.1.2 on 2018-10-23 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=15), default=None, help_text='Puoi inserire max 10 parole chiave per il tuo articolo', size=10),
            preserve_default=False,
        ),
    ]
