# Generated by Django 2.1.2 on 2018-11-06 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articolo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, help_text='Puoi inserire max 10 parole chiave per il tuo articolo', max_length=10, size=None),
        ),
    ]
