# Generated by Django 2.1.2 on 2018-10-27 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articolo', '0001_initial'),
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='id_autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autore.Autore'),
        ),
        migrations.AlterUniqueTogether(
            name='commento',
            unique_together={('id_articolo', 'id')},
        ),
    ]
