# Generated by Django 2.1.2 on 2018-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articolo', '0002_articolo_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='keywords',
        ),
    ]
