# Generated by Django 2.1.2 on 2018-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('nick', models.CharField(help_text='Max 15 caratteri', max_length=15, unique=True)),
                ('data_nascita', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(help_text='Min 4 caratteri', max_length=20)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'get_latest_by': ['-nome', '-cognome'],
            },
        ),
    ]
