# Generated by Django 2.1.2 on 2018-10-26 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField(default=datetime.date.today, editable=False)),
                ('bio', models.TextField(blank=True)),
                ('profilo_pubblico', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Autori',
                'get_latest_by': ['-(User.objects.get(pk=self.user)).first_name', '-(User.objects.get(pk=self.user)).last_name'],
            },
        ),
    ]
