# Generated by Django 2.1.2 on 2018-10-26 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autore',
            name='id',
        ),
        migrations.AlterField(
            model_name='autore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
