# Generated by Django 2.1.2 on 2018-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
