# Generated by Django 2.1.2 on 2018-11-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autore', '0003_auto_20181109_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autore',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='autore',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='autore',
            name='staff',
        ),
    ]
